### PR TITLE
Add a new line to the tooltip

### PR DESCRIPTION
**Pull request by gralp-1**
As described in my issue #105 I think this will fix it but I'm not certain.

### CODE REVIEW

**Comment by zabi94** [comment]
I doubt this will actually work. As described in the issue, tooltips are not this straightforward

**Comment by gralp-1** [comment]
> 
> 
> I doubt this will actually work. As described in the issue, tooltips are not this straightforward

I can try it out now to save the effort

**Comment by zabi94** [comment]
That would be ideal, I just don't have the time lately

**Comment by gralp-1** [comment]
when I run it from the source code the item isn't there anymore. That is to say that the item with that tooltip.

**Comment by zabi94** [comment]
change `zabi.minecraft.extraalchemy.items.PotionRingItem.java`, line 60 to `if (true) {` to force that error to appear on every ring for testing

**Comment by gralp-1** [comment]
I've been poking around at it for a while and I can't make it work, I just get this 
image
or some combination depending on the newline character. I also tried different things like TranslatableText.

**Comment by zabi94** [comment]
Yeah, as I said in #105 tooltips break lines by splitting the tooltip into different objects, one per line, not with '\r'. '\n' or a combination of the two.

**Pull request closed without merging**
